#pragma once

#include "engine/services/iservice.h"

#include <core/data/path.h>

namespace blowbox
{
  namespace engine
  {
    /**
    * @brief The command line arguments passed into the executable.
    *
    * This directly reflects the arguments that were passed into the main() function.
    */
    struct CommandLineArguments
    {
      int argc;     //!< The CLI argument count.
      char** argv;  //!< The CLI argument values.
    };

    /**
    * @brief The command line configuration.
    *
    * This is the result of the CommandLineArguments being parsed.
    */
    struct CommandLineConfig
    {
      unsigned int logger_verbosity_level;  //!< The verbosity threshold level for the Logger.
      bool fullscreen;                      //!< Whether the app should run in fullscreen or not.
      int width;                            //!< The resolution of the window to be created.
      int height;                           //!< The height of the window to be created.
      Path project_directory;               //!< The directory from which the app should pull assets - i.e. the root of a given project.
    };

    /**
    * @brief Processes the command line arguments.
    * 
    * Parses the command line arguments and makes them easily
    * easily accessible to the rest of the engine. The application
    * itself cannot modify the values inside of the config
    * generated by the service, as it's purpose is to reflect
    * what the -user- wants the engine to do. Use the method
    * GetCommandLineConfig() to access the config.
    */
    class ConfigService : public IService<ConfigService>
    {
    public:
      /**
      * @brief Constructs a ConfigService.
      * @remarks To parse the command line, use the ConfigService::ParseCLI() method.
      */
      ConfigService();

      /**
      * @brief Destructs a ConfigService.
      */
      virtual ~ConfigService();

      /**
      * @brief Initializes the ConfigService.
      */
      virtual void Initialize() override;

      /**
      * @brief Shuts down the ConfigService.
      */
      virtual void Shutdown() override;

      /**
      * @brief Parses the command line arguments and creates a CommandLineConfig from it.
      * @param[in] argc The number of arguments received through your main() function.
      * @param[in] argv The values of the arguments received through your main() function.
      */
      void ParseCLI(int argc, char** argv);

      /**
      * @brief Parses the command line arguments and creates a CommandLineConfig from it.
      * @param[in] arguments The command line arguments received through your main() function.
      */
      void ParseCLI(const CommandLineArguments& arguments);

      /**
      * @brief Returns the CommandLineConfig object containing all data the user passed into the program via the command line.
      * @returns The CommandLineConfig object containing all data the user passed into the program via the command line.
      */
      const CommandLineConfig& GetCommandLineConfig() const;

    private:
      /**
      * @brief Generates a default CommandLineConfig using default values.
      * @remarks This is used only as a fallback when command line parsing fails.
      */
      void GenerateDefaultCommandLineConfig();

    private:
      CommandLineArguments arguments_;  //!< The command line arguments received through main().
      CommandLineConfig cmd_config_;    //!< The configuration based on the command line arguments.
    };
  }
}